version: "3.9"
   
services:
  db:
    container_name: database
    image: postgres:alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: pms
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - "5432:5432"
  api_server:
    container_name: api_server
    build: ./server
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000" 
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    environment:
        DEBUG: 1
        PORT: 8000
    depends_on:
      - db