# Generated by Django 3.2.3 on 2021-05-22 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_patient_doctors'),
        ('sensor_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='value',
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='users.patient'),
        ),
        migrations.CreateModel(
            name='SingleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('sensor_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='sensor_data.sensordata')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='sensor_data.measurementtype')),
            ],
        ),
    ]
