# Generated by Django 3.2.3 on 2021-05-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0003_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(null=True, to='users.Doctor'),
        ),
    ]
