# Generated by Django 3.2.3 on 2021-05-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_patient_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(null=True, related_name='patients', to='users.Doctor'),
        ),
    ]
